S = File;
File =;
File = FunctionDeclaration, File;

FunctionDeclaration = "func", id, "(", ")", CodeBlock;
FunctionDeclaration = "func", id, "(", ")", "->", "(", ")", CodeBlock;
FunctionDeclaration = "func", id, "(", ")", "->", Type, CodeBlock;
FunctionDeclaration = "func", id, "(", ")", "->", "(", Type, ")", CodeBlock;
FunctionDeclaration = "func", id, "(", ParamList, ")", CodeBlock;
FunctionDeclaration = "func", id, "(", ParamList, ")", "->", "(", ")", CodeBlock;
FunctionDeclaration = "func", id, "(", ParamList, ")", "->", Type, CodeBlock;
FunctionDeclaration = "func", id, "(", ParamList, ")", "->", "(", Type, ")", CodeBlock;

ParamList = id, ":", Type;
ParamList = id, ":", Type, ParamList;

Type = id;
Type = "*", Type;
Type = "[", "]", Type;
Type = "[", int, "]", Type;

CodeBlock = "{", StatementList, "}";

StatementList =;
StatementList = Statement, StatementList;

Statement = ";";
Statement = Expression, ";";
Statement = Declaration, ";";
Statement = "return", ";";
Statement = "return", Expression, ";";
Statement = CodeBlock;
Statement = IfBlock;
Statement = Loop;

Loop = "while", "(", Expression, ")", CodeBlock;

IfBlock = "if", "(", Expression, ")", CodeBlock;
IfBlock = "if", "(", Expression, ")", CodeBlock, "else", IfBlock;
IfBlock = "if", "(", Expression, ")", CodeBlock, "else", CodeBlock;

Declaration = id, ":", Type, "=", Expression;

Expression = AssignmentExpression;

AssignmentExpression = EqualityExpression, AssignmentOperator, AssignmentExpression;
AssignmentExpression = EqualityExpression;

EqualityExpression = RelationalExpression, EqualityOperator, RelationalExpression;
EqualityExpression = RelationalExpression;

RelationalExpression = AdditiveExpression, RelationalOperator, AdditiveExpression;
RelationalExpression = AdditiveExpression;

AdditiveExpression = MultiplicativeExpression, AdditiveOperator, MultiplicativeExpression;
AdditiveExpression = MultiplicativeExpression;

MultiplicativeExpression = UnaryExpression, MultiplicativeOperator, UnaryExpression;
MultiplicativeExpression = UnaryExpression;

UnaryExpression = UnaryOperator, UnaryExpression;
UnaryExpression = PostfixExpression;

PostfixExpression = PrimaryExpression, "(", ExpressionList, ")";
PostfixExpression = PrimaryExpression, "[", Expression, "]";
PostfixExpression = PrimaryExpression;

PrimaryExpression = id;
PrimaryExpression = Literal;
PrimaryExpression = "(", Expression, ")";
PrimaryExpression = "new", Type, "(", ExpressionList, ")";
PrimaryExpression = "[", "]", Type, "{", ExpressionList, "}";
PrimaryExpression = "[", int, "]", Type, "{", ExpressionList, "}";

ExpressionList = ;
ExpressionList = Expression;
ExpressionList = Expression, ",", ExpressionList;

FunctionCall = Expression, "(", ExpressionList, ")";
